"use strict";

// API base: same origin by default (the C++ server hosts this UI).
// Override with ?api=http://host:port when serving the UI separately.
const API = (new URLSearchParams(location.search).get("api") || "").replace(/\/$/, "");
const MAX_FILE_BYTES = 10 * 1024 * 1024;
const SUGGESTIONS = [
  "What is LocalMind?",
  "How does retrieval work?",
  "Which models can I use?",
];

const $ = (id) => document.getElementById(id);
const els = {
  sidebar: $("sidebar"),
  sidebarToggle: $("sidebar-toggle"),
  dropzone: $("dropzone"),
  fileInput: $("file-input"),
  pasteToggle: $("paste-toggle"),
  pasteForm: $("paste-form"),
  pasteName: $("paste-name"),
  pasteText: $("paste-text"),
  pasteCancel: $("paste-cancel"),
  docList: $("doc-list"),
  docEmpty: $("doc-empty"),
  docCount: $("doc-count"),
  stats: $("stats"),
  status: $("status"),
  messages: $("messages"),
  welcome: $("welcome"),
  suggestions: $("suggestions"),
  composer: $("composer"),
  question: $("question"),
  send: $("send"),
  toast: $("toast"),
};

// ---------------------------------------------------------------- helpers

async function api(path, options = {}) {
  const init = { ...options, headers: { ...(options.headers || {}) } };
  if (init.body !== undefined && typeof init.body !== "string") {
    init.body = JSON.stringify(init.body);
    init.headers["Content-Type"] = "application/json";
  }
  let res;
  try {
    res = await fetch(API + path, init);
  } catch {
    throw new Error("Cannot reach the LocalMind server.");
  }
  if (res.status === 204) return null;
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || `Request failed (HTTP ${res.status})`);
  return data;
}

function el(tag, props = {}, ...children) {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(props)) {
    if (k === "class") node.className = v;
    else if (k.startsWith("on")) node.addEventListener(k.slice(2), v);
    else if (v !== undefined && v !== null) node.setAttribute(k, v);
  }
  for (const c of children) if (c !== null && c !== undefined) node.append(c);
  return node;
}

let toastTimer;
function toast(message, isError = false) {
  els.toast.textContent = message;
  els.toast.classList.toggle("error", isError);
  els.toast.hidden = false;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => (els.toast.hidden = true), isError ? 6000 : 3000);
}

function formatChars(n) {
  if (n >= 1e6) return (n / 1e6).toFixed(1) + "M chars";
  if (n >= 1e3) return (n / 1e3).toFixed(1) + "k chars";
  return n + " chars";
}

function scrollToBottom() {
  els.messages.scrollTop = els.messages.scrollHeight;
}

// ---------------------------------------------------------------- status

async function refreshHealth() {
  try {
    const h = await api("/api/health");
    const llm = h.llm;
    if (llm.enabled && llm.available) {
      setStatus("ok", llm.name.replace(/^ollama:/, ""), `Answers generated by ${llm.name}. Embeddings: ${h.embedder}`);
    } else if (llm.enabled) {
      setStatus("warn", "extractive", `${llm.name} is not reachable - answers are extracted from passages. Embeddings: ${h.embedder}`);
    } else {
      setStatus("warn", "extractive", `LLM disabled - answers are extracted from passages. Embeddings: ${h.embedder}`);
    }
  } catch {
    setStatus("down", "offline", "Cannot reach the LocalMind server");
  }
}

function setStatus(kind, text, title) {
  els.status.className = "status " + kind;
  els.status.textContent = text;
  els.status.title = title;
}

// ---------------------------------------------------------------- documents

async function refreshDocuments(flashId) {
  try {
    const [{ documents }, stats] = await Promise.all([api("/api/documents"), api("/api/stats")]);
    renderDocuments(documents, flashId);
    els.stats.textContent =
      `${stats.chunks} chunks · ${formatChars(stats.chars)} · ${stats.embedder}`;
  } catch (e) {
    els.stats.textContent = e.message;
  }
}

function renderDocuments(docs, flashId) {
  els.docList.replaceChildren(
    ...docs.map((d) => {
      const li = el(
        "li",
        { "data-id": d.id, title: d.name },
        el(
          "div",
          { class: "doc-meta" },
          el("div", { class: "doc-name" }, d.name),
          el("div", { class: "doc-sub" }, `${d.chunks} chunk${d.chunks === 1 ? "" : "s"} · ${formatChars(d.chars)}`),
        ),
        el("button", {
          class: "doc-del",
          type: "button",
          "aria-label": `Remove ${d.name}`,
          title: "Remove",
          onclick: () => removeDocument(d),
        }, "✕"),
      );
      if (d.id === flashId) li.classList.add("flash");
      return li;
    }),
  );
  els.docCount.textContent = docs.length;
  els.docEmpty.hidden = docs.length > 0;
}

async function addDocument(name, text) {
  const doc = await api("/api/documents", { method: "POST", body: { name, text } });
  toast(doc.duplicate ? `“${doc.name}” is already indexed` : `Indexed “${name}” (${doc.chunks} chunk${doc.chunks === 1 ? "" : "s"})`);
  await refreshDocuments(doc.id);
}

async function uploadFiles(files) {
  els.dropzone.classList.add("busy");
  try {
    for (const file of files) {
      if (/\.pdf$/i.test(file.name)) {
        toast(`${file.name}: PDF is not supported yet - export it as text first`, true);
        continue;
      }
      if (file.size > MAX_FILE_BYTES) {
        toast(`${file.name} is larger than 10 MB`, true);
        continue;
      }
      try {
        await addDocument(file.name, await file.text());
      } catch (e) {
        toast(`${file.name}: ${e.message}`, true);
      }
    }
  } finally {
    els.dropzone.classList.remove("busy");
    els.fileInput.value = "";
  }
}

async function removeDocument(doc) {
  if (!confirm(`Remove “${doc.name}” from the index?`)) return;
  try {
    await api(`/api/documents/${doc.id}`, { method: "DELETE" });
    toast(`Removed “${doc.name}”`);
    await refreshDocuments();
  } catch (e) {
    toast(e.message, true);
  }
}

// ---------------------------------------------------------------- chat

function addMessage(who, ...content) {
  els.welcome.hidden = true;
  const msg = el("div", { class: `msg ${who}` }, el("div", { class: "bubble" }, ...content));
  els.messages.append(msg);
  scrollToBottom();
  return msg;
}

// Turns "text [1] more [2][3]" into text nodes and clickable citation chips.
function renderAnswer(text, msg) {
  const parts = [];
  const re = /\[(\d{1,2})\]/g;
  let last = 0;
  let m;
  while ((m = re.exec(text))) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    const n = m[1];
    parts.push(el("button", {
      class: "cite",
      type: "button",
      title: `Show source ${n}`,
      onclick: () => showSource(msg, n),
    }, n));
    last = re.lastIndex;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

function showSource(msg, n) {
  const src = msg.querySelector(`.source[data-n="${n}"]`);
  if (!src) return;
  src.open = true;
  src.classList.add("highlight");
  src.scrollIntoView({ behavior: "smooth", block: "nearest" });
  setTimeout(() => src.classList.remove("highlight"), 1500);
}

function renderSources(sources) {
  return el(
    "div",
    { class: "sources" },
    ...sources.map((s) =>
      el(
        "details",
        { class: "source", "data-n": s.n },
        el(
          "summary",
          {},
          el("span", { class: "n" }, `[${s.n}]`),
          el("span", { class: "name" }, `${s.document_name} · part ${s.chunk_index + 1}`),
          el("span", { class: "score" }, s.score.toFixed(2)),
        ),
        el("p", {}, s.text),
      ),
    ),
  );
}

let busy = false;

async function ask(question) {
  if (busy) return;
  busy = true;
  els.send.disabled = true;
  addMessage("user", question);
  const pending = addMessage("ai", el("span", { class: "typing", "aria-label": "Thinking" }, el("i"), el("i"), el("i")));

  try {
    const r = await api("/api/query", { method: "POST", body: { question } });
    const bubble = pending.querySelector(".bubble");
    bubble.replaceChildren(...renderAnswer(r.answer, pending));

    const modeLabel = { llm: "generated", extractive: "extracted from passages", empty: "no matches" }[r.mode] || r.mode;
    pending.append(
      el(
        "div",
        { class: "meta" },
        el("span", {}, `${modeLabel} · ${(r.took_ms / 1000).toFixed(1)}s`),
        r.warning ? el("span", { class: "warn", title: r.warning }, "⚠ LLM unavailable") : null,
      ),
    );
    if (r.sources.length) pending.append(renderSources(r.sources));
  } catch (e) {
    pending.classList.add("error");
    pending.querySelector(".bubble").textContent = "⚠ " + e.message;
  } finally {
    busy = false;
    els.send.disabled = false;
    scrollToBottom();
    els.question.focus();
  }
}

function autosize() {
  els.question.style.height = "auto";
  els.question.style.height = Math.min(els.question.scrollHeight, 180) + "px";
}

// ---------------------------------------------------------------- wiring

els.composer.addEventListener("submit", (e) => {
  e.preventDefault();
  const q = els.question.value.trim();
  if (!q) return;
  els.question.value = "";
  autosize();
  ask(q);
});

els.question.addEventListener("input", autosize);
els.question.addEventListener("keydown", (e) => {
  if (e.key === "Enter" && !e.shiftKey && !e.isComposing) {
    e.preventDefault();
    els.composer.requestSubmit();
  }
});

els.fileInput.addEventListener("change", () => uploadFiles([...els.fileInput.files]));
els.dropzone.addEventListener("keydown", (e) => {
  if (e.key === "Enter" || e.key === " ") {
    e.preventDefault();
    els.fileInput.click();
  }
});
for (const type of ["dragenter", "dragover"]) {
  els.dropzone.addEventListener(type, (e) => {
    e.preventDefault();
    els.dropzone.classList.add("over");
  });
}
for (const type of ["dragleave", "drop"]) {
  els.dropzone.addEventListener(type, () => els.dropzone.classList.remove("over"));
}
els.dropzone.addEventListener("drop", (e) => {
  e.preventDefault();
  uploadFiles([...e.dataTransfer.files]);
});

els.pasteToggle.addEventListener("click", () => {
  els.pasteForm.hidden = !els.pasteForm.hidden;
  if (!els.pasteForm.hidden) els.pasteName.focus();
});
els.pasteCancel.addEventListener("click", () => {
  els.pasteForm.hidden = true;
  els.pasteForm.reset();
});
els.pasteForm.addEventListener("submit", async (e) => {
  e.preventDefault();
  const submit = els.pasteForm.querySelector("button[type=submit]");
  submit.disabled = true;
  try {
    await addDocument(els.pasteName.value.trim(), els.pasteText.value);
    els.pasteForm.reset();
    els.pasteForm.hidden = true;
  } catch (err) {
    toast(err.message, true);
  } finally {
    submit.disabled = false;
  }
});

els.sidebarToggle.addEventListener("click", () => els.sidebar.classList.toggle("open"));
document.addEventListener("click", (e) => {
  if (els.sidebar.classList.contains("open") && !els.sidebar.contains(e.target) && e.target !== els.sidebarToggle) {
    els.sidebar.classList.remove("open");
  }
});

els.suggestions.replaceChildren(
  ...SUGGESTIONS.map((s) => el("button", { type: "button", onclick: () => ask(s) }, s)),
);

refreshHealth();
refreshDocuments();
setInterval(refreshHealth, 30000);
